spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8001

spring: 
  profiles: dev
    application: 
      name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03
    username: root
    password: root

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.cyh.spring.cloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: cyh-microservicecloud
  company.name: www.cyh.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

spring: 
  profiles: test
    application: 
      name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.cyh.spring.cloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: cyh-microservicecloud
  company.name: www.cyh.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
